version: '3.3'

services:
  web:
    image: odoo:17.0
    user: root
    depends_on:
      - db
    ports:
      - "8069:8069"
    volumes:
      - type: bind
        source: "./payment_zru"
        target: "/mnt/extra-addons/payment_zru"
  db:
    image: postgres:14
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata
volumes:
    odoo-db-data: